#!/usr/bin/env bash

# This assumes that it is running as superuser, so chowns the files as
# teamcity later.

TEAMCITY_DIR={{TEAMCITY_DIR}}
TEAMCITY_DATA_DIR={{TEAMCITY_DATA_DIR}}
TEAMCITY_USER={{TEAMCITY_USER}}
TEAMCITY_GROUP={{TEAMCITY_GROUP}}
TEAMCITY_VAGRANT_DIR={{TEAMCITY_VAGRANT_DIR}}

RESTORE_LATEST=TeamCity_Backup.zip
BACKUP_DIR=$TEAMCITY_DATA_DIR/backup
RESTORE_DIR=$TEAMCITY_VAGRANT_DIR/restore

# I don't know why JAVA HOME is not coming through appropriately but it's
# something to think about
export JAVA_HOME=/usr/lib/jvm/java-8-oracle

$TEAMCITY_DIR/bin/maintainDB.sh backup --all --data-dir $TEAMCITY_DATA_DIR

# Empty the restore path of the out-dated backup file
rm -f $RESTORE_DIR/$RESTORE_LATEST

LAST_BACKUP=$(ls $BACKUP_DIR | tail -n1)

cp $BACKUP_DIR/$LAST_BACKUP $RESTORE_DIR/$RESTORE_LATEST

# Now that we have the backup in place on the host machine, we can clear out this folder
rm -rf $TEAMCITY_DATA_DIR/backup
