#!/usr/bin/env bash

set -x

# clean up any dangling containers
docker container prune -f

# ...any dangling networks
docker network prune -f

# clean up any dangling data volumes
docker volume prune -f

# clean up all images
docker image prune -f -a
