#!/usr/bin/env bash
export VAULT_ADDR='https://support.montagu.dide.ic.ac.uk:8200'
if [ -z $VAULT_AUTH_GITHUB_TOKEN ]; then
    echo -n "Paste your github token: "
    read -s VAULT_AUTH_GITHUB_TOKEN
fi
export VAULT_AUTH_GITHUB_TOKEN

set -e
vault login -method=github > /dev/null

REGISTRY_URL=docker.montagu.dide.ic.ac.uk:5000
REGISTRY_USER=vimc
REGISTRY_PASSWORD=$(vault read -field=password /secret/registry/${REGISTRY_USER})

HUB_USER=$(vault read -field=username /secret/vimc-robot/dockerhub)
HUB_PASSWORD=$(vault read -field=password /secret/vimc-robot/dockerhub)

if [ -z $REGISTRY_PASSWORD ]; then
    echo "Failed to fetch registry password from vault"
    exit 1
fi

if [ -z $HUB_PASSWORD ]; then
    echo "Failed to fetch hub password from vault"
    exit 1
fi

echo $REGISTRY_PASSWORD | \
    docker login -u $REGISTRY_USER --password-stdin $REGISTRY_URL
echo $HUB_PASSWORD | \
    docker login -u $HUB_USER --password-stdin

mkdir -p ~/.ssh
vault read -field=value secret/vimc-robot/id_rsa.pub > ~/.ssh/id_rsa.pub
vault read -field=value secret/vimc-robot/id_rsa > ~/.ssh/id_rsa
chmod 600 ~/.ssh/id_rsa
touch ~/.ssh/known_hosts
if ! grep -q '^github.com' ~/.ssh/known_hosts; then
    ssh-keyscan github.com >> ~/.ssh/known_hosts
fi

# NOTE: this is a fake email address for our robot account:
git config --global user.email "rich.fitzjohn+vimc@gmail.com"
git config --global user.name "vimc-robot"
