#!/usr/bin/env bash
export VAULT_ADDR='https://support.montagu.dide.ic.ac.uk:8200'
if [ -z $VAULT_AUTH_GITHUB_TOKEN ]; then
    echo -n "Paste your github token: "
    read -s VAULT_AUTH_GITHUB_TOKEN
fi
export VAULT_AUTH_GITHUB_TOKEN

set -e
vault auth -method=github > /dev/null

REGISTRY_URL=docker.montagu.dide.ic.ac.uk:5000
REGISTRY_USER=vimc
REGISTRY_PASSWORD=$(vault read -field=password /secret/registry/${REGISTRY_USER})

if [ -z $REGISTRY_PASSWORD ]; then
    echo "Failed to fetch password from vault"
    exit 1
fi

echo $REGISTRY_PASSWORD | \
    docker login -u $REGISTRY_USER --password-stdin $REGISTRY_URL

mkdir -p ~/.ssh
vault read -field=value secret/vimc-robot/id_rsa > ~/.ssh/id_rsa
vault read -field=value secret/vimc-robot/id_rsa.pub > ~/.ssh/id_rsa.pub
