#!/usr/bin/env bash
export VAULT_ADDR='https://support.montagu.dide.ic.ac.uk:8200'
if [ -z $VAULT_AUTH_GITHUB_TOKEN ]; then
    echo -n "Paste your github token: "
    read -s VAULT_AUTH_GITHUB_TOKEN
fi
export VAULT_AUTH_GITHUB_TOKEN

REGISTRY_USER=vimc
REGISTRY_PASSWORD=$(vault read -field=password /secret/registry/${REGISTRY_USER})
REGISTRY_URL=docker.montagu.dide.ic.ac.uk:5001
docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY_URL
