#!/usr/bin/env bash
export VAULT_ADDR='https://support.montagu.dide.ic.ac.uk:8200'
if [ -z $VAULT_AUTH_GITHUB_TOKEN ]; then
    echo -n "Paste your github token: "
    read -s VAULT_AUTH_GITHUB_TOKEN
fi
export VAULT_AUTH_GITHUB_TOKEN

set -e
vault auth -method=github > /dev/null

REGISTRY_URL=docker.montagu.dide.ic.ac.uk:5000
REGISTRY_USER=vimc
REGISTRY_PASSWORD=$(vault read -field=password /secret/registry/${REGISTRY_USER})

HUB_USER=vimcrobot
HUB_PASSWORD=$(vault read -field=password /secret/${HUB_USER$)
if [ -z $REGISTRY_PASSWORD ]; then
    echo "Failed to fetch registry password from vault"
    exit 1
fi

if [ -z $HUB_PASSWORD ]; then
    echo "Failed to fetch hub password from vault"
    exit 1
fi

echo $REGISTRY_PASSWORD | \
    docker login -u $REGISTRY_USER --password-stdin $REGISTRY_URL

echo $HUB_PASSWORD | \
    docker login -u $HUB_USER --password-stdin
